local harpoon = require("harpoon")

harpoon:setup()

vim.keymap.set("n", "<leader>a", function()
	harpoon:list():append()
end)
vim.keymap.set("n", "<C-e>", function()
	harpoon.ui:toggle_quick_menu(harpoon:list())
end)

vim.keymap.set("n", "<C-h>", function()
	harpoon:list():select(1)
end, { desc = "Harpoon Select 1" })
vim.keymap.set("n", "<C-j>", function()
	harpoon:list():select(2)
end, { desc = "Harpoon Select 2" })
vim.keymap.set("n", "<C-k>", function()
	harpoon:list():select(3)
end, { desc = "Harpoon Select 3" })
vim.keymap.set("n", "<C-l>", function()
	harpoon:list():select(4)
end, { desc = "Harpoon Select 4" })

-- Toggle previous & next buffers stored within Harpoon list
vim.keymap.set("n", "<C-S-j>", function()
	harpoon:list():prev()
end, { desc = "Harpoon previous buffer" })
vim.keymap.set("n", "<C-S-k>", function()
	harpoon:list():next()
end, { desc = "Harpoon next buffer" })
