vim.keymap.set({ "n", "v", "s", "o" }, "<C-K>", "<Plug>(wintabs_previous)")
vim.keymap.set({ "n", "v", "s", "o" }, "<C-L>", "<Plug>(wintabs_next)")
vim.keymap.set({ "n", "v", "s", "o" }, "<C-T>c", "<Plug>(wintabs_close)")
vim.keymap.set({ "n", "v", "s", "o" }, "<C-T>u", "<Plug>(wintabs_undo)")
vim.keymap.set({ "n", "v", "s", "o" }, "<C-T>o", "<Plug>(wintabs_only)")
vim.keymap.set({ "n", "v", "s", "o" }, "<C-W>c", "<Plug>(wintabs_close_window)")
vim.keymap.set({ "n", "v", "s", "o" }, "<C-W>o", "<Plug>(wintabs_only_window)")

vim.api.nvim_create_user_command("Tabc", "WintabsCloseVimtab", {})
vim.api.nvim_create_user_command("Tabo", "WintabsOnlyVimtab", {})
